import { test, expect, userId } from './account-fixture.js';
import { mockYouTube } from './youtube-fixture.js';
import { seedClips } from '../src/data.js';
const id = '22222222-2222-4222-8222-222222222222';
const original = {...seedClips[0], id, title:'My original scene', start:7.3, end:10.4, tags:['work'], originalId:'old-id'};
async function openEditor(page) {
  await mockYouTube(page); await page.goto('/');
  await page.getByRole('button',{name:`Play: ${original.title}`,exact:true}).click();
  await page.getByRole('button',{name:'Edit clip',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'Clip player'})).toHaveCount(0);
  await expect(page.getByRole('dialog',{name:'Edit clip'})).toBeVisible();
}
test('owner edits timing and metadata in place; favorites, share link, ownership and hidden metadata survive reload',async({page,accountState})=>{
  accountState.clips=[{id,owner_id:userId,data:{...original}}];
  accountState.favorites=[{owner_id:userId,clip_id:id}];
  accountState.shared={...original};
  await openEditor(page);
  await expect(page.getByLabel('Clip title')).toHaveValue(original.title);
  await expect(page.getByLabel('Start',{exact:true})).toHaveValue('0:07.3');
  await expect(page.getByLabel('End',{exact:true})).toHaveValue('0:10.4');
  await page.getByLabel('Start',{exact:true}).fill('8.5');
  await page.getByLabel('End',{exact:true}).fill('12.7');
  await page.getByLabel('Clip title').fill('Updated scene');
  await page.getByRole('combobox',{name:/Reaction/}).selectOption('😂 Humor');
  await page.getByText('Additional options',{exact:true}).click();
  await page.getByLabel('Movie, series, or channel').fill('Updated source');
  await page.getByLabel('Character / creator').fill('Updated speaker');
  await page.getByLabel('Tags',{exact:true}).fill('work, friday');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'Clip player'}).getByRole('heading',{name:'Updated scene'})).toBeVisible();
  expect(accountState.clips).toHaveLength(1);
  expect(accountState.clips[0]).toMatchObject({id,owner_id:userId,data:{id,start:8.5,end:12.7,title:'Updated scene',source:'Updated source',speaker:'Updated speaker',tags:['work','friday'],quote:original.quote,originalId:'old-id'}});
  expect(accountState.favorites[0].clip_id).toBe(id);
  await page.reload();
  await expect(page.getByRole('button',{name:'Play: Updated scene',exact:true})).toBeVisible();
  await page.goto('/c/'+'a'.repeat(24));
  await expect(page.getByRole('dialog',{name:'Clip player'}).getByRole('heading',{name:'Updated scene'})).toBeVisible();
  await expect.poll(()=>page.evaluate(()=>window.testPlayer.range)).toMatchObject({startSeconds:8.5,endSeconds:12.7});
});
test('cancel discards edits; failed save and invalid timing preserve draft for retry',async({page,accountState})=>{
  accountState.clips=[{id,owner_id:userId,data:{...original}}];
  await openEditor(page);
  await page.getByLabel('Clip title').fill('Discard this');
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  expect(accountState.clips[0].data.title).toBe(original.title);
  await page.getByRole('button',{name:'Edit clip',exact:true}).click();
  await expect(page.getByLabel('Clip title')).toHaveValue(original.title);
  await page.getByLabel('End',{exact:true}).fill('1');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Choose a valid range');
  await page.getByLabel('End',{exact:true}).fill('12');
  await page.getByLabel('Clip title').fill('Retry scene');
  accountState.failSave=true;
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Storage unavailable');
  expect(accountState.clips[0].data.title).toBe(original.title);
  await expect(page.getByLabel('Clip title')).toHaveValue('Retry scene');
  accountState.failSave=false;
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'Edit clip'})).toHaveCount(0);
  expect(accountState.clips[0].data.title).toBe('Retry scene');
});
for(const legacy of [false,true]) test(`admin edits ${legacy?'migrated':'another user’s'} clip without adding it to My clips`,async({page,accountState})=>{
  accountState.role='admin';
  accountState.managed=[{...original,...(legacy?{id:'legacy:legacytest000001',_kind:'legacy',_legacyLink:'legacytest000001'}:{_kind:'saved'})}];
  await openEditor(page);
  await page.getByLabel('Clip title').fill('Admin updated');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'Edit clip'})).toHaveCount(0);
  expect(accountState.clips).toHaveLength(0);
  expect(accountState.managed[0].title).toBe('Admin updated');
  await page.reload();
  await expect(page.getByRole('button',{name:'Play: Admin updated',exact:true})).toBeVisible();
});
test('member cannot edit another person’s clip or an example',async({page,accountState})=>{
  accountState.managed=[{...original,_kind:'saved'}];
  await mockYouTube(page); await page.goto('/');
  await page.getByRole('button',{name:`Play: ${original.title}`,exact:true}).click();
  await expect(page.getByRole('button',{name:'Edit clip',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Close',exact:true}).click();
  await page.getByRole('button',{name:'Play: No. God. Please, no!',exact:true}).click();
  await expect(page.getByRole('button',{name:'Edit clip',exact:true})).toHaveCount(0);
});
test('mobile edit supports changing video and keeps controls inside the dialog',async({page,accountState})=>{
  accountState.clips=[{id,owner_id:userId,data:{...original}}];
  await page.setViewportSize({width:390,height:844});
  await openEditor(page);
  await page.getByRole('button',{name:'Change link',exact:true}).click();
  await expect(page.getByLabel('YouTube link')).toHaveValue(`https://www.youtube.com/watch?v=${original.videoId}`);
  await page.getByLabel('YouTube link').fill('https://youtu.be/dQw4w9WgXcQ');
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await expect(page.getByLabel('Start',{exact:true})).toHaveValue('');
  await page.getByLabel('Start',{exact:true}).fill('5.1');
  await page.getByLabel('End',{exact:true}).fill('8.6');
  await expect(page.getByRole('button',{name:'Play video',exact:true})).toBeEnabled();
  expect(await page.evaluate(()=>window.testPlayer.state)).not.toBe(1);
  const dialog=page.getByRole('dialog',{name:'Edit clip'});
  expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
  await page.getByRole('button',{name:'Save changes',exact:true}).scrollIntoViewIfNeeded();
  await page.screenshot({path:'/tmp/clipquote-edit-mobile.png'});
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await expect(dialog).toHaveCount(0);
  expect(accountState.clips[0].data).toMatchObject({id,videoId:'dQw4w9WgXcQ',start:5.1,end:8.6});
});
